package com.teachingassistant.util;

import java.util.HashMap;
import java.util.Map;

public class AppConstants {

	public static final String USER_DETAILS_INSERT_QRY = "INSERT INTO USER_DETAILS(FIRST_NAME,LAST_NAME,MOBILE_NUMBER,EMAIL_ADDRESS,USER_TYPE,USER_NAME,PASSWORD,CREATE_TIME,LAST_UPDATE_TIME) VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";
	public static final String USER_DETAILS_SELECT_QRY = "SELECT USER_ID,FIRST_NAME,LAST_NAME,MOBILE_NUMBER,EMAIL_ADDRESS,USER_TYPE,USER_NAME,PASSWORD FROM USER_DETAILS WHERE (USER_NAME = ? or MOBILE_NUMBER = ? or EMAIL_ADDRESS = ?) and PASSWORD = ?";
	public static final String USER_DETAILS_UPDATE_QRY = "UPDATE USER_DETAILS SET FIRST_NAME=?,LAST_NAME=?,MOBILE_NUMBER=?,EMAIL_ADDRESS=?,PASSWORD=?,LAST_UPDATE_TIME=CURRENT_TIMESTAMP WHERE USER_ID=?";
	public static final String USERNAME_EXIST_CHECK_SELECT_QRY = "SELECT USER_ID FROM USER_DETAILS WHERE USER_NAME = ?";
	public static final String MOBILENO_EXIST_CHECK_SELECT_QRY = "SELECT USER_ID FROM USER_DETAILS WHERE MOBILE_NUMBER = ?";
	public static final String EMAIL_EXIST_CHECK_SELECT_QRY = "SELECT USER_ID FROM USER_DETAILS WHERE EMAIL_ADDRESS = ?";

	public static final String UPDATE_MOBILENO_EXIST_CHECK_SELECT_QRY = "SELECT USER_ID FROM USER_DETAILS WHERE MOBILE_NUMBER = ? and USER_ID<>?";
	public static final String UPDATE_EMAIL_EXIST_CHECK_SELECT_QRY = "SELECT USER_ID FROM USER_DETAILS WHERE EMAIL_ADDRESS = ? and USER_ID<>?";

	public static final String USER_COURSE_CHECK_SELECT_QRY = "SELECT COURSE_ID FROM USER_COURSES WHERE USER_ID=? AND COURSE_ID=?";

	/* user application registration start */
	public static final String USER_JOB_APPLICATION_INSERT_QRY = "INSERT INTO USER_APPLICATION_DETAILS"
			+ "(USER_ID,STUDENT_ID,QUALIFICATION,PREV_EXP_PRESENT,CV_FILE_NAME,CREATE_TIME,LAST_UPDATE_TIME,APPLICATION_ID) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,concat('TA',FLOOR(rand() * 90000000 + 10000000)))";

	public static final String USER_COURSE_INSERT_QRY = "INSERT INTO USER_COURSES(USER_ID,COURSE_ID,APPLICATION_STATUS,CREATE_TIME,LAST_UPDATE_TS) VALUES (?,?,'PENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";

	public static final String USER_PREV_EXP_COURSE_INSERT_QRY = "INSERT INTO USER_PREV_EXP_COURSES(USER_ID,COURSE_ID,FROM_DATE,TO_DATE) VALUES(?,?,?,?)";

	public static final String UPDATE_TA_APPLICATION_DTLS = "UPDATE USER_APPLICATION_DETAILS SET QUALIFICATION=?,CV_FILE_NAME=?,LAST_UPDATE_TIME=CURRENT_TIMESTAMP WHERE USER_ID=?";
	public static final String UPDATE_TA_QUALIFICATION = "UPDATE USER_APPLICATION_DETAILS SET QUALIFICATION=?,LAST_UPDATE_TIME=CURRENT_TIMESTAMP WHERE USER_ID=?";
	public static final String UPDATE_APPLICANT_DTLS_LAST_UPDATE_TS = "UPDATE USER_APPLICATION_DETAILS SET LAST_UPDATE_TIME=CURRENT_TIMESTAMP WHERE USER_ID=?";
	/* user application registration end */

	public static final String COURSE_DTLS_SELECT_QRY = "SELECT COURSE_ID,COURSE_NAME,PROFESSOR_ID,OPEN_POSITIONS FROM COURSE_DETAILS";

	public static final String COURSE_INSERT_QRY = "INSERT INTO COURSE_DETAILS(COURSE_ID,COURSE_NAME,PROFESSOR_ID,OPEN_POSITIONS,CREATE_TIME,LAST_UPDATE_TIME) VALUES(?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)";

	public static final String COURSE_DELETE_QRY = "DELETE FROM COURSE_DETAILS WHERE COURSE_ID=?";
	public static final String COURSE_UPDATE_QRY = "UPDATE COURSE_DETAILS SET OPEN_POSITIONS=? WHERE COURSE_ID=?";

	/* application tracking start */

	public static final String CHECK_EXISTING_APPLICANT = "SELECT USER_ID FROM USER_APPLICATION_DETAILS WHERE USER_ID=?";

	public static final String APPLICANT_COURSEWISE_STATUS_TRACKING_DTLS_SEL_QRY = "SELECT COURSE_END_DATE,t4.EMAIL_ADDRESS as EMAIL_ADDRESS, t3.APPLICATION_ID as APPLICATION_ID, t2.COURSE_ID as COURSE_ID, COURSE_NAME, APPLICATION_STATUS, OFFER_STATUS, IS_RECOMMENDED, IS_NOTIFIED,APPLICANT_COURSE_UNIQUE_ID FROM USER_COURSES"
			+ " t1, COURSE_DETAILS t2, USER_APPLICATION_DETAILS t3,PROFESSOR_DETAILS t4"
			+ " WHERE t1.COURSE_ID=t2.COURSE_ID AND t1.USER_ID=t3.USER_ID"
			+ " AND t2.PROFESSOR_ID=t4.PROFESSOR_ID AND t1.USER_ID=? ORDER BY t1.LAST_UPDATE_TS DESC";

	public static final String APPLICANT_COURSE_STATUS_TRACKING_DTLS_SEL_QRY = "SELECT"
			+ " t1.PERFORMANCE_RATING as PERFORMANCE_RATING,t1.INSTRUCTOR_FEEDBACK as INSTRUCTOR_FEEDBACK,COURSE_START_DATE,COURSE_END_DATE,OFFER_ACCEPTED_ON,OFFER_REJECTED_ON,FEEDBACK_GIVEN_DATE,RECOMMENDED_ON,NOTIFIED_ON,COURSE_APPROVED_TS,COURSE_REJECTED_TS,LAST_UPDATE_TS,"
			+ "t4.EMAIL_ADDRESS as EMAIL_ADDRESS, t3.APPLICATION_ID as APPLICATION_ID, t2.COURSE_ID as COURSE_ID, COURSE_NAME, APPLICATION_STATUS, OFFER_STATUS, IS_RECOMMENDED, IS_NOTIFIED FROM USER_COURSES"
			+ " t1, COURSE_DETAILS t2, USER_APPLICATION_DETAILS t3,PROFESSOR_DETAILS t4"
			+ " WHERE t1.COURSE_ID=t2.COURSE_ID AND t1.USER_ID=t3.USER_ID"
			+ " AND t2.PROFESSOR_ID=t4.PROFESSOR_ID AND t1.USER_ID=? AND t1.COURSE_ID=? AND APPLICANT_COURSE_UNIQUE_ID=?";

	public static final String APPLICANT_OLD_COURSE_STATUS_TRACKING_DTLS_SEL_QRY = "SELECT"
			+ " INSTRUCTOR_FEEDBACK,COURSE_START_DATE,COURSE_END_DATE,OFFER_ACCEPTED_ON,OFFER_REJECTED_ON,FEEDBACK_GIVEN_DATE,RECOMMENDED_ON,NOTIFIED_ON,COURSE_APPROVED_TS,COURSE_REJECTED_TS,LAST_UPDATE_TS,"
			+ "t4.EMAIL_ADDRESS as EMAIL_ADDRESS, t3.APPLICATION_ID as APPLICATION_ID, t2.COURSE_ID as COURSE_ID, COURSE_NAME, APPLICATION_STATUS, OFFER_STATUS, IS_RECOMMENDED, IS_NOTIFIED FROM USER_COURSES"
			+ " t1, COURSE_DETAILS t2, USER_APPLICATION_DETAILS t3,PROFESSOR_DETAILS t4"
			+ " WHERE t1.COURSE_ID=t2.COURSE_ID AND t1.USER_ID=t3.USER_ID"
			+ " AND t2.PROFESSOR_ID=t4.PROFESSOR_ID AND t1.USER_ID=? AND t1.COURSE_ID=?";
	/* application tracking end */

	/* get applicant details for admin and committee start */

	public static final String GET_JOB_APPLICANTS_WITH_COURSE_ID_STATUS_SEL_QRY = "SELECT a.*,b.EMAIL_ADDRESS as instrctorEmail,b.MOBILE_NUMBER as instrctorMobileNo from(SELECT "
			+ "IS_RECOMMENDED,IS_NOTIFIED,COURSE_START_DATE,COURSE_END_DATE,OFFER_ACCEPTED_ON,OFFER_REJECTED_ON,FEEDBACK_GIVEN_DATE,RECOMMENDED_ON,NOTIFIED_ON,COURSE_APPROVED_TS,COURSE_REJECTED_TS,"
			+ "userAppDtls.USER_ID as USER_ID,FIRST_NAME, LAST_NAME, STUDENT_ID, QUALIFICATION, PREV_EXP_PRESENT, CV_FILE_NAME,APPLICATION_STATUS, OFFER_STATUS"
			+ ",COURSE_NAME,userCourses.CREATE_TIME as courseApplicationTime, userCourses.COURSE_ID as COURSE_ID,PERFORMANCE_RATING,userAppDtls.APPLICATION_ID as APPLICATION_ID,userCourses.INSTRUCTOR_FEEDBACK as INSTRUCTOR_FEEDBACK,OPEN_POSITIONS"
			+ ",prfDtls.EMAIL_ADDRESS as prfEmail,prfDtls.MOBILE_NO as prfMobileNo,INSTRUCTOR_ID"

			+ " FROM USER_APPLICATION_DETAILS userAppDtls, USER_COURSES userCourses,"
			+ " COURSE_DETAILS courseMaster, USER_DETAILS userDtls,PROFESSOR_DETAILS prfDtls"

			+ " WHERE userDtls.USER_ID = userAppDtls.USER_ID AND userAppDtls.USER_ID = userCourses.USER_ID"
			+ " AND userCourses.COURSE_ID = courseMaster.COURSE_ID"
			+ " AND prfDtls.PROFESSOR_ID=courseMaster.PROFESSOR_ID AND userCourses.COURSE_ID = ?"
			+ " AND userCourses.APPLICATION_STATUS = ? AND userDtls.USER_ID=? AND APPLICANT_COURSE_UNIQUE_ID=?)a LEFT JOIN USER_DETAILS b  on (a.INSTRUCTOR_ID=b.USER_ID)";

	public static final String GET_ALL_JOB_APPLICANTS_WITH_STATUS_SEL_QRY = "SELECT a.*,b.EMAIL_ADDRESS as instrctorEmail,b.MOBILE_NUMBER as instrctorMobileNo from(SELECT "
			+ "IS_RECOMMENDED,IS_NOTIFIED,COURSE_START_DATE,COURSE_END_DATE,OFFER_ACCEPTED_ON,OFFER_REJECTED_ON,FEEDBACK_GIVEN_DATE,RECOMMENDED_ON,NOTIFIED_ON,COURSE_APPROVED_TS,COURSE_REJECTED_TS,"
			+ "userAppDtls.USER_ID as USER_ID,FIRST_NAME, LAST_NAME, STUDENT_ID, QUALIFICATION, PREV_EXP_PRESENT, CV_FILE_NAME,APPLICATION_STATUS, OFFER_STATUS"
			+ ",COURSE_NAME,userCourses.CREATE_TIME as courseApplicationTime, userCourses.COURSE_ID as COURSE_ID,PERFORMANCE_RATING,userAppDtls.APPLICATION_ID as APPLICATION_ID,userCourses.INSTRUCTOR_FEEDBACK as INSTRUCTOR_FEEDBACK,OPEN_POSITIONS"
			+ ",prfDtls.EMAIL_ADDRESS as prfEmail,prfDtls.MOBILE_NO as prfMobileNo,INSTRUCTOR_ID"

			+ " FROM USER_APPLICATION_DETAILS userAppDtls, USER_COURSES userCourses,"
			+ " COURSE_DETAILS courseMaster, USER_DETAILS userDtls,PROFESSOR_DETAILS prfDtls"

			+ " WHERE userDtls.USER_ID = userAppDtls.USER_ID AND userAppDtls.USER_ID = userCourses.USER_ID"
			+ " AND userCourses.COURSE_ID = courseMaster.COURSE_ID"
			+ " AND prfDtls.PROFESSOR_ID=courseMaster.PROFESSOR_ID"
			+ " AND userCourses.APPLICATION_STATUS = ? AND userDtls.USER_ID=? AND APPLICANT_COURSE_UNIQUE_ID=?)a LEFT JOIN USER_DETAILS b  on (a.INSTRUCTOR_ID=b.USER_ID)";

	/*
	 * public static final String
	 * GET_OLD_JOB_APPLICANTS_WITH_COURSE_ID_STATUS_SEL_QRY =
	 * "SELECT a.*,b.EMAIL_ADDRESS as instrctorEmail,b.MOBILE_NUMBER as instrctorMobileNo from(SELECT "
	 * +
	 * "IS_RECOMMENDED,IS_NOTIFIED,COURSE_START_DATE,COURSE_END_DATE,OFFER_ACCEPTED_ON,OFFER_REJECTED_ON,FEEDBACK_GIVEN_DATE,RECOMMENDED_ON,NOTIFIED_ON,COURSE_APPROVED_TS,COURSE_REJECTED_TS,"
	 * +
	 * "userAppDtls.USER_ID as USER_ID,FIRST_NAME, LAST_NAME, STUDENT_ID, QUALIFICATION, PREV_EXP_PRESENT, CV_FILE_NAME,APPLICATION_STATUS, OFFER_STATUS"
	 * +
	 * ",COURSE_NAME,userCourses.CREATE_TIME as courseApplicationTime, userCourses.COURSE_ID as COURSE_ID,PERFORMANCE_RATING,userAppDtls.APPLICATION_ID as APPLICATION_ID,userCourses.INSTRUCTOR_FEEDBACK as INSTRUCTOR_FEEDBACK,OPEN_POSITIONS"
	 * +
	 * ",prfDtls.EMAIL_ADDRESS as prfEmail,prfDtls.MOBILE_NO as prfMobileNo,INSTRUCTOR_ID"
	 * 
	 * + " FROM USER_APPLICATION_DETAILS userAppDtls, USER_COURSES userCourses," +
	 * " COURSE_DETAILS courseMaster, USER_DETAILS userDtls,PROFESSOR_DETAILS prfDtls"
	 * 
	 * +
	 * " WHERE userDtls.USER_ID = userAppDtls.USER_ID AND userAppDtls.USER_ID = userCourses.USER_ID"
	 * + " AND userCourses.COURSE_ID = courseMaster.COURSE_ID" +
	 * " AND prfDtls.PROFESSOR_ID=courseMaster.PROFESSOR_ID AND userCourses.COURSE_ID = ?"
	 * +
	 * " AND userCourses.APPLICATION_STATUS = ? AND userDtls.USER_ID=?)a LEFT JOIN USER_DETAILS b  on (a.INSTRUCTOR_ID=b.USER_ID)"
	 * ;
	 * 
	 * public static final String GET_OLD_ALL_JOB_APPLICANTS_WITH_STATUS_SEL_QRY =
	 * "SELECT a.*,b.EMAIL_ADDRESS as instrctorEmail,b.MOBILE_NUMBER as instrctorMobileNo from(SELECT "
	 * +
	 * "IS_RECOMMENDED,IS_NOTIFIED,COURSE_START_DATE,COURSE_END_DATE,OFFER_ACCEPTED_ON,OFFER_REJECTED_ON,FEEDBACK_GIVEN_DATE,RECOMMENDED_ON,NOTIFIED_ON,COURSE_APPROVED_TS,COURSE_REJECTED_TS,"
	 * +
	 * "userAppDtls.USER_ID as USER_ID,FIRST_NAME, LAST_NAME, STUDENT_ID, QUALIFICATION, PREV_EXP_PRESENT, CV_FILE_NAME,APPLICATION_STATUS, OFFER_STATUS"
	 * +
	 * ",COURSE_NAME,userCourses.CREATE_TIME as courseApplicationTime, userCourses.COURSE_ID as COURSE_ID,PERFORMANCE_RATING,userAppDtls.APPLICATION_ID as APPLICATION_ID,userCourses.INSTRUCTOR_FEEDBACK as INSTRUCTOR_FEEDBACK,OPEN_POSITIONS"
	 * +
	 * ",prfDtls.EMAIL_ADDRESS as prfEmail,prfDtls.MOBILE_NO as prfMobileNo,INSTRUCTOR_ID"
	 * 
	 * + " FROM USER_APPLICATION_DETAILS userAppDtls, USER_COURSES userCourses," +
	 * " COURSE_DETAILS courseMaster, USER_DETAILS userDtls,PROFESSOR_DETAILS prfDtls"
	 * 
	 * +
	 * " WHERE userDtls.USER_ID = userAppDtls.USER_ID AND userAppDtls.USER_ID = userCourses.USER_ID"
	 * + " AND userCourses.COURSE_ID = courseMaster.COURSE_ID" +
	 * " AND prfDtls.PROFESSOR_ID=courseMaster.PROFESSOR_ID" +
	 * " AND userCourses.APPLICATION_STATUS = ? AND userDtls.USER_ID=?)a LEFT JOIN USER_DETAILS b  on (a.INSTRUCTOR_ID=b.USER_ID)"
	 * ;
	 */

	/* get applicant details for admin and committee end */

	public static final String GET_USER_PREV_COURSES_SELECT_QRY = "SELECT t2.COURSE_NAME as COURSE_NAME,FROM_DATE,TO_DATE FROM USER_PREV_EXP_COURSES t1,"
			+ "COURSE_DETAILS t2 WHERE t1.COURSE_ID=t2.COURSE_ID AND t1.USER_ID=?";

	public static final String GET_USER_APPLN_COURSE_DTLS_SEL_QRY = "SELECT userAppDtls.USER_ID as USER_ID, STUDENT_ID, QUALIFICATION, PREV_EXP_PRESENT, CV_FILE_NAME,APPLICATION_STATUS, OFFER_STATUS"
			+ " ,COURSE_ID,userAppDtls.APPLICATION_ID as APPLICATION_ID,COURSE_END_DATE,OFFER_REJECTED_ON,COURSE_REJECTED_TS"

			+ " FROM USER_APPLICATION_DETAILS userAppDtls, USER_COURSES userCourses"

			+ " WHERE userCourses.USER_ID = userAppDtls.USER_ID AND userCourses.USER_ID = ?";

	public static final String GET_TA_APPLICANT_USER_DTLS_SEL_QRY = "SELECT USER_ID,LAST_NAME,FIRST_NAME FROM USER_DETAILS WHERE USER_TYPE='TA Applicant'";

	/* committee approve/reject start */
	public static final String UPDATE_TA_APPLICANT_COURSE_APPROVE_STATUS = "UPDATE USER_COURSES SET APPLICATION_STATUS=?,COURSE_APPROVED_TS=CURRENT_TIMESTAMP,LAST_UPDATE_TS=CURRENT_TIMESTAMP WHERE USER_ID=? AND COURSE_ID=? AND APPLICATION_STATUS='PENDING' AND APPLICANT_COURSE_UNIQUE_ID=?";
	public static final String UPDATE_TA_APPLICANT_COURSE_REJECT_STATUS = "UPDATE USER_COURSES SET APPLICATION_STATUS=?,COURSE_REJECTED_TS=CURRENT_TIMESTAMP,LAST_UPDATE_TS=CURRENT_TIMESTAMP WHERE USER_ID=? AND COURSE_ID=? AND APPLICATION_STATUS='PENDING' AND APPLICANT_COURSE_UNIQUE_ID=?";
	/* committee approve/reject end */

	/* admin recommend/notify start */
	public static final String UPDATE_TA_APPLICANT_COURSE_STAUS_RECOMMEND_FLAG = "UPDATE USER_COURSES SET IS_RECOMMENDED=?,RECOMMENDED_ON=CURRENT_TIMESTAMP,LAST_UPDATE_TS=CURRENT_TIMESTAMP WHERE USER_ID=? AND COURSE_ID=? AND APPLICATION_STATUS='PENDING' AND APPLICANT_COURSE_UNIQUE_ID=?";
	public static final String UPDATE_TA_APPLICANT_COURSE_STAUS_NOTIFY_FLAG = "UPDATE USER_COURSES SET IS_NOTIFIED=?,NOTIFIED_ON=CURRENT_TIMESTAMP,LAST_UPDATE_TS=CURRENT_TIMESTAMP WHERE USER_ID=? AND COURSE_ID=? AND APPLICATION_STATUS IN ('APPROVED','REJECTED') AND APPLICANT_COURSE_UNIQUE_ID=?";
	/* admin recommend/notify end */

	/* TA Applicant will accept/decline offer - start */
	public static final String UPDATE_TA_OFFER_STATUS = "UPDATE USER_COURSES SET OFFER_STATUS=?,APPLICATION_STATUS=?,OFFER_ACCEPTED_ON=?,OFFER_REJECTED_ON=?,COURSE_START_DATE=?,LAST_UPDATE_TS=? WHERE COURSE_ID=? AND USER_ID=? AND APPLICATION_STATUS='APPROVED'";
	/* TA Applicant will accept/decline offer - end */

	public static final String UPDATE_TA_CV_FILENAME = "UPDATE USER_APPLICATION_DETAILS SET CV_FILE_NAME=? WHERE USER_ID=?";

	/* update TA performance - rating/feedback by instructor start */

	public static final String GET_APPOINTED_APPLICANTS_SEL_QRY = "SELECT userAppDtls.USER_ID as USER_ID,FIRST_NAME, LAST_NAME, STUDENT_ID, QUALIFICATION, PREV_EXP_PRESENT, CV_FILE_NAME,APPLICATION_STATUS, OFFER_STATUS"
			+ " ,COURSE_NAME,userCourses.CREATE_TIME as courseApplicationTime, userCourses.COURSE_ID as COURSE_ID"
			+ " ,userCourses.IS_RECOMMENDED as IS_RECOMMENDED, userCourses.IS_NOTIFIED as IS_NOTIFIED,userAppDtls.APPLICATION_ID as APPLICATION_ID"

			+ " FROM USER_APPLICATION_DETAILS userAppDtls, USER_COURSES userCourses,"
			+ " COURSE_DETAILS courseMaster, USER_DETAILS userDtls"

			+ " WHERE userDtls.USER_ID = userAppDtls.USER_ID AND userAppDtls.USER_ID = userCourses.USER_ID"
			+ " AND userCourses.COURSE_ID = courseMaster.COURSE_ID"
			+ " AND userCourses.APPLICATION_STATUS = 'APPOINTED'";

	public static final String UPDATE_TA_PERFORMANCE = "UPDATE USER_COURSES SET PERFORMANCE_RATING=?,INSTRUCTOR_FEEDBACK=?,INSTRUCTOR_ID=?,FEEDBACK_GIVEN_DATE=CURRENT_TIMESTAMP,LAST_UPDATE_TS=CURRENT_TIMESTAMP,COURSE_END_DATE=CURRENT_TIMESTAMP,APPLICATION_STATUS='COMPLETED' WHERE USER_ID=? and COURSE_ID=? AND APPLICATION_STATUS='APPOINTED'";
	/* update TA performance - rating/feedback by instructor end */

	public static final String GET_PROFESSOR_DTLS_SEL_QRY = "SELECT PROFESSOR_ID,NAME,MOBILE_NO,EMAIL_ADDRESS FROM PROFESSOR_DETAILS";

	public static final String GET_PROFESSOR_DTLS_FOR_COURSEID_SEL_QRY = "SELECT t1.PROFESSOR_ID as PROFESSOR_ID,NAME,MOBILE_NO,EMAIL_ADDRESS,COURSE_ID,COURSE_NAME,OPEN_POSITIONS FROM PROFESSOR_DETAILS t1,"
			+ "COURSE_DETAILS t2 WHERE t1.PROFESSOR_ID = t2.PROFESSOR_ID AND COURSE_ID = ?";
	public static final String SEPARATOR_FOR_RESPONSE = "@@SEPARATOR@@";

	public static final String CHECK_APPLICANT_ELIGIBLE_FOR_COURSE = "SELECT 1 FROM USER_COURSES WHERE USER_ID=? AND COURSE_ID=? AND (COURSE_END_DATE <> NULL OR OFFER_REJECTED_ON <> NULL OR COURSE_REJECTED_DATE <> NULL)";

//	public static final String GET_APPLICANT_COURSES_BY_STATUS_AND_USERID_SEL_QRY = "SELECT APPLICANT_COURSE_UNIQUE_ID,t1.USER_ID as USER_ID,t3.COURSE_ID as COURSE_ID,t3.COURSE_NAME as COURSE_NAME,APPLICATION_ID,CV_FILE_NAME,IS_RECOMMENDED FROM USER_APPLICATION_DETAILS t1,"
//			+ "USER_COURSES t2,COURSE_DETAILS t3 WHERE t1.USER_ID=t2.USER_ID"
//			+ " AND t2.COURSE_ID=t3.COURSE_ID AND t1.USER_ID=? AND APPLICATION_STATUS=? ORDER BY t2.LAST_UPDATE_TS DESC";
	

	public static final String GET_ALL_APPLICANT_COURSES_BY_COURSEID_AND_STATUS_SEL_QRY = "SELECT APPLICANT_COURSE_UNIQUE_ID,t1.USER_ID as USER_ID,t3.COURSE_ID as COURSE_ID,t3.COURSE_NAME as COURSE_NAME,APPLICATION_ID,CV_FILE_NAME,IS_RECOMMENDED FROM USER_APPLICATION_DETAILS t1,"
			+ "USER_COURSES t2,COURSE_DETAILS t3 WHERE t1.USER_ID=t2.USER_ID"
			+ " AND t2.COURSE_ID=t3.COURSE_ID AND t2.COURSE_ID=? AND APPLICATION_STATUS=? ORDER BY t2.LAST_UPDATE_TS DESC";
	

//	public static final String GET_ALL_APPLICANT_COURSES_BY_STATUS_SEL_QRY = "SELECT APPLICANT_COURSE_UNIQUE_ID,t1.USER_ID as USER_ID,t3.COURSE_ID as COURSE_ID,t3.COURSE_NAME as COURSE_NAME,APPLICATION_ID,CV_FILE_NAME,IS_RECOMMENDED FROM USER_APPLICATION_DETAILS t1,"
//			+ "USER_COURSES t2,COURSE_DETAILS t3 WHERE t1.USER_ID=t2.USER_ID"
//			+ " AND t2.COURSE_ID=t3.COURSE_ID AND APPLICATION_STATUS=? ORDER BY t2.LAST_UPDATE_TS DESC";
	


//	public static final String GET_ALL_APPLICANT_COURSES_SEL_QRY = "SELECT APPLICANT_COURSE_UNIQUE_ID,t1.USER_ID as USER_ID,t3.COURSE_ID as COURSE_ID,t3.COURSE_NAME as COURSE_NAME,APPLICATION_ID,CV_FILE_NAME,IS_RECOMMENDED FROM USER_APPLICATION_DETAILS t1,"
//			+ "USER_COURSES t2,COURSE_DETAILS t3 WHERE t1.USER_ID=t2.USER_ID"
//			+ " AND t2.COURSE_ID=t3.COURSE_ID ORDER BY t2.LAST_UPDATE_TS DESC";
//	

	public static final String GET_APPLICANT_COURSES_SEL_QRY = "SELECT APPLICATION_STATUS,APPLICANT_COURSE_UNIQUE_ID,t1.USER_ID as USER_ID,t3.COURSE_ID as COURSE_ID,t3.COURSE_NAME as COURSE_NAME,APPLICATION_ID,CV_FILE_NAME,IS_RECOMMENDED FROM USER_APPLICATION_DETAILS t1,"
			+ "USER_COURSES t2,COURSE_DETAILS t3 WHERE t1.USER_ID=t2.USER_ID"
			+ " AND t2.COURSE_ID=t3.COURSE_ID";

	public static final String CHECK_OPEN_POSITIONS_FOR_COURSE = "SELECT OPEN_POSITIONS-(SELECT COUNT(1) FROM USER_COURSES WHERE COURSE_ID=? AND APPLICATION_STATUS IN ('APPROVED','APPOINTED'))"
			+ "AS OPEN_POSITIONS FROM COURSE_DETAILS WHERE COURSE_ID=?";
	
	public static final String GET_USER_DETAILS_BASED_ON_USERTYPE_SEL_QRY = "SELECT USER_ID,FIRST_NAME,LAST_NAME,MOBILE_NUMBER,EMAIL_ADDRESS,USER_NAME,CREATE_TIME,LAST_UPDATE_TIME FROM USER_DETAILS WHERE USER_TYPE = ?";

	public static Map<String, String> getQualification() {
		Map<String, String> qualificationMap = new HashMap<>();
		qualificationMap.put("DEPLOMA", "High School Deploma");
		qualificationMap.put("BACHELORS", "Bachelors Degree");
		qualificationMap.put("MASTERS", "Masters Degree");
		return qualificationMap;

	}

	public static Map<String, String> getRatingDesc() {
		Map<String, String> ratingDescMap = new HashMap<>();
		ratingDescMap.put("EXCELLENT", "Excellent");
		ratingDescMap.put("GOOD", "Good");
		ratingDescMap.put("AVERAGE", "Average");
		ratingDescMap.put("BELOWAVERAGE", "Below Average");
		return ratingDescMap;

	}
}
